import React, { useState, useEffect, useRef } from "react";
import { motion, AnimatePresence } from "framer-motion";
import { X, Send, Sparkles, Volume2, MessageSquare } from "lucide-react";
import axios from "axios";

type Message = {
  id: string;
  sender: "bot" | "user";
  text: string;
};

const INITIAL_KNOWLEDGE_BASE = [
  { keywords: ["book", "ticket", "reserve", "buy", "slot", "seat"], response: "You can book tickets by clicking 'Book Now' at the top or navigating to the /slots page. A standard feast costs ₹{PRICE} per person, and we have multiple slots throughout the day." },
  { keywords: ["price", "cost", "how much", "amount", "fee"], response: "The standard Madurai Kari Virundhu feast costs ₹{PRICE}. We also offer family combos and premium VIP packages." },
  { keywords: ["menu", "food", "items", "dishes", "eat", "serve"], response: "Our legendary feast includes authentic dishes! Highlights include Mutton Biryani, Kola Urundai, Kari Dosa, Madurai Jigarthanda, and Halwa. Check out the Menu page for the full list." },
  { keywords: ["admin", "dashboard", "manage", "revenue", "owner"], response: "The Admin dashboard (/admin) is a secure portal where owners can monitor total revenue, manage all bookings, toggle system feature flags, and monitor real-time system health." },
  { keywords: ["kitchen", "chef", "cook", "kds", "prepare"], response: "The Kitchen dashboard (/kitchen) acts as a Kitchen Display System (KDS). It shows real-time aggregated guest counts per slot so the culinary team knows exactly how much food to prepare without waste." },
  { keywords: ["reception", "scanner", "qr", "verify", "check-in", "guard"], response: "The Scanner module (/scanner) allows receptionists and security guards to scan the QR codes on guests' PDF tickets to securely check them in and prevent duplicate entries." },
  { keywords: ["who", "what", "about", "suvaialaya", "software", "platform"], response: "Suvaialaya is a high-performance, horizontally scalable event management and ticketing platform designed for a flagship South Indian culinary experience. It features Role-Based Access Control, Redis caching, and Razorpay integrations." },
  { keywords: ["hello", "hi", "hey", "vanakkam", "morning", "evening"], response: "Vanakkam! I'm SuvaiBot, the digital soul of Suvaialaya. I know everything about this platform—from booking tickets to our microservice architecture. How can I assist you?" },
  { keywords: ["time", "when", "hours", "open"], response: "We are open from 11 AM to 11 PM. Booking slots are available at 11:00 AM, 1:00 PM, 3:00 PM, 5:00 PM, 7:00 PM, and 9:00 PM." },
  { keywords: ["contact", "support", "help", "issue", "problem"], response: "If you need immediate assistance, please reach out to the Reception desk. For developers, check the ARCHITECTURE.md generated by our AI Engine for emergency runbooks." },
  { keywords: ["tech", "stack", "react", "node", "database", "redis"], response: "The software is built with a modern stack: React (Vite) on the frontend, Node.js & Express on the backend, MongoDB for persistence, Redis for caching and queues, and Tailwind CSS for styling." },
  { keywords: ["cancel", "refund", "change"], response: "Bookings can be cancelled from the user dashboard. Refunds are processed automatically based on our 24-hour cancellation policy via the Razorpay gateway." },
  { keywords: ["developed", "creator", "developer", "author", "made by", "who made", "shalini"], response: "This premium software product is developed by Shalini N." }
];

export function SuvaiBot() {
  const [isOpen, setIsOpen] = useState(false);
  const [messages, setMessages] = useState<Message[]>([
    { id: "msg-0", sender: "bot", text: "Vanakkam! I'm SuvaiBot. Ask me anything about the platform, booking tickets, or our software architecture!" }
  ]);
  const [input, setInput] = useState("");
  const [basePrice, setBasePrice] = useState(1499); // Fallback price
  const messagesEndRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    // Fetch active event to get the dynamic base price from the database
    axios.get("/api/events")
      .then((res) => {
        if (res.data.success && res.data.data.length > 0) {
          setBasePrice(res.data.data[0].basePrice);
        }
      })
      .catch((err) => console.error("Failed to fetch event for bot pricing", err));
  }, []);

  useEffect(() => {
    messagesEndRef.current?.scrollIntoView({ behavior: "smooth" });
  }, [messages]);

  const handleSend = () => {
    if (!input.trim()) return;

    const userText = input.trim();
    const newMsg: Message = { id: Date.now().toString(), sender: "user", text: userText };
    setMessages(prev => [...prev, newMsg]);
    setInput("");

    // Simple NLP Keyword Matching
    setTimeout(() => {
      const lowerInput = userText.toLowerCase();
      let bestResponse = "That's an interesting question! As the SuvaiBot, I specialize in helping you navigate the Suvaialaya platform, booking feasts, and explaining our software modules. Could you rephrase?";
      
      let maxMatches = 0;
      for (const entry of INITIAL_KNOWLEDGE_BASE) {
        const matches = entry.keywords.filter(kw => lowerInput.includes(kw)).length;
        if (matches > maxMatches) {
          maxMatches = matches;
          // Inject dynamic price from database
          bestResponse = entry.response.replace("{PRICE}", basePrice.toString());
        }
      }

      setMessages(prev => [...prev, { id: (Date.now() + 1).toString(), sender: "bot", text: bestResponse }]);
    }, 600);
  };

  return (
    <div className="fixed bottom-6 right-6 z-[150] flex flex-col items-end pointer-events-none">
      
      {/* Persistent Speech Bubble when closed */}
      <AnimatePresence>
        {!isOpen && (
          <motion.div
            initial={{ opacity: 0, y: 10, scale: 0.9 }}
            animate={{ opacity: 1, y: 0, scale: 1 }}
            exit={{ opacity: 0, scale: 0.9, y: 10 }}
            className="bg-white text-black px-4 py-3 rounded-2xl rounded-br-sm shadow-xl border-2 border-[#C9841A]/30 mb-4 max-w-[200px] pointer-events-auto cursor-pointer"
            onClick={() => setIsOpen(true)}
          >
            <p className="text-xs font-bold leading-snug">
              Ready to Explore Madurai? <br/> Ask me about events and food!
            </p>
          </motion.div>
        )}
      </AnimatePresence>

      {/* Chat Window */}
      <AnimatePresence>
        {isOpen && (
          <motion.div 
            initial={{ opacity: 0, y: 20, scale: 0.95 }}
            animate={{ opacity: 1, y: 0, scale: 1 }}
            exit={{ opacity: 0, y: 20, scale: 0.95 }}
            className="w-80 sm:w-96 bg-[#16120D] border-2 border-[#C9841A]/30 rounded-3xl shadow-2xl overflow-hidden flex flex-col font-sans mb-4 pointer-events-auto"
          >
            {/* Header */}
            <div className="px-6 py-4 bg-gradient-to-r from-[#C9841A]/20 to-transparent border-b border-[#C9841A]/20 flex items-center justify-between">
              <div className="flex items-center gap-3">
                <div className="w-10 h-10 rounded-full bg-[#C9841A] flex items-center justify-center text-black shadow-lg shadow-[#C9841A]/20">
                  <Sparkles size={18} />
                </div>
                <div>
                  <h3 className="text-white text-sm font-bold tracking-widest uppercase font-display">SuvaiBot</h3>
                  <p className="text-[10px] text-[#C9841A] uppercase tracking-widest font-bold">Cultural Guide</p>
                </div>
              </div>
              <button onClick={() => setIsOpen(false)} className="text-white/50 hover:text-white transition-colors bg-white/5 p-2 rounded-full">
                <X size={16} />
              </button>
            </div>

            {/* Chat Area */}
            <div className="h-[280px] overflow-y-auto p-6 flex flex-col gap-4 bg-[url('https://www.transparenttextures.com/patterns/cream-paper.png')] bg-opacity-5">
              {messages.map((m) => (
                <div key={m.id} className={`flex ${m.sender === 'user' ? 'justify-end' : 'justify-start'}`}>
                  <div className={`max-w-[85%] px-4 py-3 rounded-2xl text-sm shadow-md ${m.sender === 'user' ? 'bg-[#C9841A] text-black rounded-tr-sm font-medium' : 'bg-[#2A241B] border border-[#C9841A]/20 text-white rounded-tl-sm'}`}>
                    {m.text}
                  </div>
                </div>
              ))}
              <div ref={messagesEndRef} />
            </div>

            {/* Suggestions */}
            <div className="px-4 pb-2 pt-2 bg-[#16120D] flex flex-wrap gap-2 border-t border-white/5">
              {["How to book?", "What's on the menu?", "Admin dashboard?"].map((suggestion, i) => (
                <button 
                  key={i}
                  onClick={() => setInput(suggestion)}
                  className="px-4 py-2 bg-[#C9841A]/10 border border-[#C9841A]/30 rounded-full text-xs font-bold text-[#C9841A] hover:bg-[#C9841A] hover:text-black transition-all"
                >
                  {suggestion}
                </button>
              ))}
            </div>

            {/* Input Area */}
            <div className="p-4 bg-[#16120D] flex items-center gap-2">
              <input 
                type="text" 
                value={input}
                onChange={(e) => setInput(e.target.value)}
                onKeyDown={(e) => e.key === 'Enter' && handleSend()}
                placeholder="Ask about Madurai..."
                className="flex-1 bg-white/5 border border-white/10 rounded-full px-4 py-3 text-sm text-white placeholder:text-white/30 focus:outline-none focus:border-[#C9841A]/50 transition-colors"
              />
              <button 
                onClick={handleSend}
                className="w-12 h-12 rounded-full bg-[#C9841A] flex items-center justify-center text-black hover:bg-[#E09528] transition-colors shadow-lg shadow-[#C9841A]/20"
              >
                <Send size={18} />
              </button>
            </div>
          </motion.div>
        )}
      </AnimatePresence>

      {/* Elegant Chat Button */}
      <motion.button 
        whileHover={{ scale: 1.05 }}
        whileTap={{ scale: 0.95 }}
        onClick={() => setIsOpen(!isOpen)}
        className="relative z-[160] pointer-events-auto shadow-[0_8px_30px_rgb(0,0,0,0.12)] rounded-full overflow-hidden flex items-center justify-center w-16 h-16 bg-gradient-to-tr from-[#1a3d2b] to-[#2d6a4f] border-2 border-[#c9841a]/30"
      >
        <div className="absolute inset-0 bg-[url('https://www.transparenttextures.com/patterns/cubes.png')] opacity-20 mix-blend-overlay"></div>
        <AnimatePresence mode="wait">
          {isOpen ? (
            <motion.div key="close" initial={{ rotate: -90, opacity: 0 }} animate={{ rotate: 0, opacity: 1 }} exit={{ rotate: 90, opacity: 0 }} transition={{ duration: 0.2 }}>
              <X className="text-white" size={28} />
            </motion.div>
          ) : (
            <motion.div key="chat" initial={{ rotate: 90, opacity: 0 }} animate={{ rotate: 0, opacity: 1 }} exit={{ rotate: -90, opacity: 0 }} transition={{ duration: 0.2 }}>
              <MessageSquare className="text-[#c9841a]" size={28} />
            </motion.div>
          )}
        </AnimatePresence>
        
        {/* Subtle ping effect behind */}
        {!isOpen && (
          <div className="absolute inset-0 rounded-full bg-[#c9841a] opacity-20 animate-ping" style={{ animationDuration: '3s' }}></div>
        )}
      </motion.button>
    </div>
  );
}
